config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'main' => "homes#main"
  get 'error' => "homes#error"

  # userがログインしている時のrootページ
  authenticated :user do
    root "homes#main", as: :authenticated_root  # Pathは一意でなければならないため被らないように名前をつける
  end

  # 未ログイン時のrootページ
  devise_scope :user do
    root 'homes#top'
  end

  post 'onesignal/:user_id/add', to: 'users#onesignal_add', as: 'onesignal_add'
  post 'onesignal/:user_id/remove', to: 'users#onesignal_remove', as: 'onesignal_remove'

  resources :users, only: [:show, :edit, :update, :destroy] do
    get 'unsubscribe' => "users#unsubscribe"
    get 'favorites' => 'favorites#favorite'
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :introduces, only: [:index, :create, :new, :edit, :update, :destroy]
  end

  resources :posts, only: [:index, :create, :edit, :update, :destroy, :show] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :rooms, only: [:create, :show, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :matches, only: [:index, :destroy, :create]

  patch 'matches/matching' => "matches#matching"
  get "search" => "searches#search"

  namespace :admin do
    root to: 'homes#top'

    resources :rooms, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :introduces, only: [:index, :show, :destroy]
    get "search" => "searches#search"
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  #cancancanによる権限確認(followings/followersは除外)
  load_and_authorize_resource only: [:create, :destroy]

#フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer, notice: "フォローしました:)"
  end
#フォローを外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer, notice: "フォローを外しました:)"
  end
#フォロー一覧
  def followings
    @user = User.find(params[:user_id])
    @users = @user.followings.page(params[:page]).per(11)
  end
#フォロワー一覧
  def followers
    @user = User.find(params[:user_id])
    @users = @user.followers.page(params[:page]).per(11)
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 offset-1">
      <h2 class="heading mt-4"><%= @user.nickname %>さんの<%= follow %>一覧</h2>
    </div>
    <div class="col-xl-3 col-sm-11 side m-2">
      <%= render 'users/info', user: current_user %>
    </div>
    <div class="col-xl-8 col-sm-11">
      <% if users.exists? %>
        <table class="table box">
          <% users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_image(50,50) %></td>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.nickname %>
                <% end %>
              </td>
              <td>フォロー数：<%= user.followings.count %></td>
              <td>フォロワー数：<%= user.followers.count %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <p class="mt-3">ユーザーはまだいません</p>
      <% end %>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/relationships/_follow_btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: 'btn btn-secondary' %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<%= render 'follow', users: @users, follow: "フォロワー" %>

app/views/relationships/followings.html.erb
<%= render 'follow', users: @users, follow: "フォロー" %>