config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'main' => "homes#main"
  get 'error' => "homes#error"

  # userがログインしている時のrootページ
  authenticated :user do
    root "homes#main", as: :authenticated_root  # Pathは一意でなければならないため被らないように名前をつける
  end

  # 未ログイン時のrootページ
  devise_scope :user do
    root 'homes#top'
  end

  post 'onesignal/:user_id/add', to: 'users#onesignal_add', as: 'onesignal_add'
  post 'onesignal/:user_id/remove', to: 'users#onesignal_remove', as: 'onesignal_remove'

  resources :users, only: [:show, :edit, :update, :destroy] do
    get 'unsubscribe' => "users#unsubscribe"
    get 'favorites' => 'favorites#favorite'
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :introduces, only: [:index, :create, :new, :edit, :update, :destroy]
  end

  resources :posts, only: [:index, :create, :edit, :update, :destroy, :show] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :rooms, only: [:create, :show, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :matches, only: [:index, :destroy, :create]

  patch 'matches/matching' => "matches#matching"
  get "search" => "searches#search"

  namespace :admin do
    root to: 'homes#top'

    resources :rooms, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :introduces, only: [:index, :show, :destroy]
    get "search" => "searches#search"
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:top, :about]

  def top
  end

  def main
    @post = Post.new
    @posts = Post.preload([:user, :tags]).order(created_at: "DESC").limit(3)
    @match = Match.find_by(user_id: current_user.id)
  end

  def about
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 offset-1">
      <h2 class="heading mt-4">管理者トップページ</h2>
    </div>
  </div>
  <div class="row mt-3 text-center admin">
    <div class="col-md-3 admin-btn">
      <%= link_to admin_users_path do %>
        <p>ユーザー一覧</p>
      <% end %>
    </div>
    <div class="col-md-3 admin-btn">
      <%= link_to admin_posts_path do %>
        <p>投稿一覧</p>
      <% end %>
    </div>
    <div class="col-md-3 admin-btn">
      <%= link_to admin_introduces_path do %>
        <p>紹介文一覧</p>
      <% end %>
    </div>
    <div class="col-md-3 admin-btn">
      <%= link_to admin_rooms_path do %>
        <p>ルーム一覧</p>
      <% end %>
    </div>
  </div>
</div>