config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'main' => "homes#main"
  get 'error' => "homes#error"

  # userがログインしている時のrootページ
  authenticated :user do
    root "homes#main", as: :authenticated_root  # Pathは一意でなければならないため被らないように名前をつける
  end

  # 未ログイン時のrootページ
  devise_scope :user do
    root 'homes#top'
  end

  post 'onesignal/:user_id/add', to: 'users#onesignal_add', as: 'onesignal_add'
  post 'onesignal/:user_id/remove', to: 'users#onesignal_remove', as: 'onesignal_remove'

  resources :users, only: [:show, :edit, :update, :destroy] do
    get 'unsubscribe' => "users#unsubscribe"
    get 'favorites' => 'favorites#favorite'
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :introduces, only: [:index, :create, :new, :edit, :update, :destroy]
  end

  resources :posts, only: [:index, :create, :edit, :update, :destroy, :show] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :rooms, only: [:create, :show, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :matches, only: [:index, :destroy, :create]

  patch 'matches/matching' => "matches#matching"
  get "search" => "searches#search"

  namespace :admin do
    root to: 'homes#top'

    resources :rooms, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :introduces, only: [:index, :show, :destroy]
    get "search" => "searches#search"
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
  belongs_to :room, optional: true

  validates :game_name, presence:true
  validates :game_hard, presence:true
  validates :room_comment, presence:true,length:{maximum:200}

  enum matching_status: {afk: 0, stand_by: 1, in_action: 2 }
  enum game_hard: {pc: 0, ps5: 1, ps4: 2, switch: 3, xbox: 4, others:5}

  def push(owner)
    params = {"app_id" => ENV['OneSignal_key'],
              "contents" => {'en' => 'matched', 'ja' => 'マッチングしました!!'},
              "include_player_ids" => [owner.user.onesignal_user_id]
            }
    uri = URI.parse('https://onesignal.com/api/v1/notifications')
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(uri.path,'Content-Type'  => 'application/json;charset=utf-8')
    request.body = params.as_json.to_json
    response = http.request(request)
    puts response.body
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  #cancancanによる権限確認
  load_and_authorize_resource

  def index
    @match = Match.new
    @match_status = Match.find_by(user_id: current_user.id)
    @room = Room.where(owner_id: current_user).or(Room.where(member_id: current_user))
    search_gamename = params[:search_gamename]
    search_gamehard = params[:search_gamehard]
    if search_gamename.present? or search_gamehard.present?
      @stand_by_users = Match.where(matching_status: "stand_by").and(Match.where(game_name: search_gamename)).or(Match.where(game_hard: search_gamehard))
    else
      @stand_by_users = Match.preload(:user).where(matching_status: "stand_by")
    end
  end

#マッチング待機状態へ
  def create
    @match = Match.new(match_params)
    @match.user_id = current_user.id
    if @match.save
      redirect_to request.referer, notice: "マッチング待機中です:)"
    else
      @room = Room.where(owner_id: current_user).or(Room.where(member_id: current_user))
      @stand_by_users = Match.preload(:user).where(matching_status: "stand_by")
      render :index
    end
  end

#マッチグ待機状態を解除
  def destroy
    match = Match.find_by(user_id: current_user.id)
    if match.matching_status == "stand_by"
      match.destroy
      redirect_to request.referer
    else
      redirect_to request.referer, alert: "マッチングが成立しています。ルームへ移動してください。"
    end
  end

  def matching
    @match = Match.find_by(user_id: current_user.id)
    @owner_match = Match.find_by(user_id: params[:user_id])
    room_check = Room.where(owner_id: params[:user_id]).or(Room.where(member_id: params[:user_id]))
    room_check2 = Room.where(owner_id: current_user.id).or(Room.where(member_id: current_user.id))
    if @owner_match.present?
# ユーザーがマッチング済みかの判定
# マッチングしていなければマッチング後にルームを作成
      if room_check.blank? and room_check2.blank?
        @room = Room.new
        @room.owner_id = params[:user_id]
        @room.member_id = current_user.id
        @room.save
# オーナー側マッチングステータスの更新
        @owner_match.matching_status = 2
        @owner_match.room_id = @room.id
        @owner_match.update(params.permit(:matching_status))
# マッチが作成されていない場合はマッチを新規作成
        if @match.blank?
          @match = Match.new
        end
        @match.matching_status = 2
        @match.user_id = current_user.id
        @match.room_id = @room.id
        @match.room_comment = @owner_match.room_comment
        @match.game_name = @owner_match.game_name
        @match.game_hard = @owner_match.game_hard
        @match.save
# マッチング相手に通知を送信
        @match.push(@owner_match)
        redirect_to room_path(@room)
      else
        redirect_to request.referer, alert: "既に他のユーザーとマッチ中です:<"
      end
    else
      redirect_to request.referer, alert: "ユーザーが待機中ではありません"
    end
  end

  private

  def match_params
    params.require(:match).permit(:matching_status, :room_comment, :game_name, :game_hard)
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/index.html.erb
<%= render 'layouts/errors', obj: @match %>
<div class="container">
  <div class="row pt-3">
    <div class="col-md-10 col-sm-12 offset-md-1 room-info">
      <p class="text-center"> マッチング機能を利用する場合、画面右下の<%= image_tag 'bell.png' %>からPush通知を許可することを推奨します。<br>
          Push通知を利用しない場合はマッチング時の通知がないのでブラウザの更新をこまめに行うことを推奨します。<br>
          また、通知はいつでも無効化することができます。<br>
          ※画面右下に<%= image_tag 'bell.png' %>が表示されない場合はブラウザの再読み込みをお試しください。
     </p>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-md-5 col-sm-12 offset-md-1">
      <h4>マッチング</h4>
      <!--NoMethodErrorを防ぐために&を活用-->
      <% if @match_status&.matching_status == "stand_by" %>
        <div class="action text-center mt-5 ">
          <%= link_to "マッチング待機解除", match_path(@match_status), method: :delete, class: 'btn btn-match' %>
        </div>
      <% elsif @match_status&.matching_status == "in_action" %>
        <div class="action text-center mt-5 ">
          <%= link_to "マッチング中(ルームへ)", room_path(@room.ids), class: 'btn btn-match', data: { 'turbolinks': false } %>
        </div>
      <% else %>
        <%= form_with model: @match do |f| %>
          <%= f.hidden_field :matching_status, value: "stand_by" %>
          <div class="field">
            <%= f.label :"ゲーム名:" %>
            <%= f.text_field :game_name, placeholder: "ゲーム名", class: 'form-control' %>
          </div>
          <div class="field">
            <%= f.label :"ハード名:" %>
            <%= f.select :game_hard, Match.game_hards_i18n.invert, {}, class: 'form-control' %>
          </div>
          <div class="field">
            <%= f.label :"ルームコメント:" %>
            <%= f.text_area :room_comment, placeholder: "ルームコメントをここに", class: 'form-control', rows: 3 %>
          </div>
          <div class="action text-right mt-2">
            <%= f.submit "マッチング待機開始", class: 'btn btn-outline-success' %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-5 col-sm-12">
      <h4>ルーム検索</h4>
      <%= form_with url: { action: 'index' }, method: :get do |f| %>
        <div class="field">
          <%= f.label :"ゲーム名:" %>
          <%= f.text_field :search_gamename, placeholder: "ゲーム名", class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :"ハード名:" %>
          <%= f.select :search_gamehard, Match.game_hards_i18n.invert, {}, class: 'form-control' %>
        </div>
        <div class="action text-right mt-2">
          <%= link_to "クリア", matches_path, class: 'btn btn-outline-success mx-4' %>
          <%= f.submit "検索", class: 'btn btn-outline-success' %>
        </div>
      <% end %>
    </div>
    <div class="col-11 offset-1">
      <h2 class="heading mt-4">待機中ユーザー</h2>
    </div>
    <div class="col-md-10 offset-md-1">
      <% if @stand_by_users.blank? %>
        <p>現在マッチング待機中のユーザーはいません。</p>
      <% else %>
        <% @stand_by_users.each do |match| %>
          <div class="match_<%= match.id %> tag">
            <table style="width:100%;">
              <td style="width:80px;"><%= image_tag match.user.get_image(50,50) %></td>
              <td><strong>
                <%= link_to user_path(match.user.id) do %>
                  <%= match.user.nickname %>
                <% end %>
              </strong></td>
              <% if match.user_id != current_user.id %>
                <td class="text-right"><%= link_to "マッチング", matches_matching_path(user_id: match.user.id), method: :patch, class: 'btn btn-info', "data-confirm" => "このユーザーとマッチングしますか？" %></td>
              <% else %>
                <td class="text-right"><p>自分</p></td>
              <% end %>
            </table>
            <p><strong>ゲーム名：</strong><%= match.game_name %></p>
            <p><strong>ハード名：</strong><%= match.game_hard_i18n %></p>
            <p><strong>ルームコメント：</strong></p>
            <p><%= safe_join(match.room_comment.split("\n"),tag(:br)) %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>