config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'main' => "homes#main"
  get 'error' => "homes#error"

  # userがログインしている時のrootページ
  authenticated :user do
    root "homes#main", as: :authenticated_root  # Pathは一意でなければならないため被らないように名前をつける
  end

  # 未ログイン時のrootページ
  devise_scope :user do
    root 'homes#top'
  end

  post 'onesignal/:user_id/add', to: 'users#onesignal_add', as: 'onesignal_add'
  post 'onesignal/:user_id/remove', to: 'users#onesignal_remove', as: 'onesignal_remove'

  resources :users, only: [:show, :edit, :update, :destroy] do
    get 'unsubscribe' => "users#unsubscribe"
    get 'favorites' => 'favorites#favorite'
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :introduces, only: [:index, :create, :new, :edit, :update, :destroy]
  end

  resources :posts, only: [:index, :create, :edit, :update, :destroy, :show] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :rooms, only: [:create, :show, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :matches, only: [:index, :destroy, :create]

  patch 'matches/matching' => "matches#matching"
  get "search" => "searches#search"

  namespace :admin do
    root to: 'homes#top'

    resources :rooms, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :introduces, only: [:index, :show, :destroy]
    get "search" => "searches#search"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations
  belongs_to :user

  validates :title, presence:true, length:{maximum:20}
  validates :body, presence:true, length:{maximum:200}

#いいね有無の判断
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

#タグ機能
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

# 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

# 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
   end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  def index
    @user = params[:user_id]
    if @user_id.blank?
      @posts = Post.preload(:user, :tags).all
    else
      @posts = Post.preload(:user, :tags).where(user_id: @user_id)
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      redirect_to admin_posts_path, notice: "投稿を削除しました"
    else
      redirect_to request.referer, alert: "投稿を削除できませんでした"
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    @tags = @post.tags
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  #cancancanによる権限確認
  load_and_authorize_resource

  def index
    @posts = Post.preload(:user, :tags).order("created_at DESC").page(params[:page]).per(6)
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:tag].split(',')
    # 重複しているタグを保存させない
    tag_list = tag_list.select{|e| tag_list.count(e) > 1}.uniq
    if @post.save
      @post.save_tag(tag_list)
      redirect_to post_path(@post.id), notice: "投稿しました:)"
    else
      @posts = Post.preload([:user, :tags]).order(created_at: "DESC").limit(3)
      @match = Match.find_by(user_id: current_user.id)
      render template: "homes/main"
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @tags = @post.tags
  end

  def edit
    @post = Post.find(params[:id])
    @tags = @post.tags.pluck(:name).join(',')
  end

  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:name].split(',')
    if @post.update(post_params)
      @post.save_tag(tag_list)
      redirect_to post_path(@post), notice: "投稿を更新しました:)"
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      redirect_to posts_path, notice: "紹介文を削除しました:)"
    else
      redirect_to request.referer, alert: "削除に失敗しました:<"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def ensure_correct_user
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to main_path, alert: "アクセス権限がありません:<"
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: npost do |f| %>
  <div class="field col-10 mx-auto">
    <%= f.label :title %>
    <%= f.text_field :title, class:'form-control' %>
  </div>

  <div class="field col-10 mx-auto">
    <%= f.label :body %>
    <%= f.text_area :body, class:'form-control', rows: 5 %>
  </div>

  <div class="field col-10 mx-auto">
    <%= f.label :"tag(,で区切ると複数タグ登録できます)" %>
    <%= f.text_field :tag, value: @tag_list, class: 'form-control' %>
  </div>

  <div class="action text-right col-10 mt-2">
    <%= f.submit "投稿", class:'btn btn-success' %>
  </div>
<% end %>

app/views/posts/_index.html.erb
<% posts.each do |post| %>
  <div class="post_<%= post.id %> post-box">
    <table>
      <td class="mx-4">
        <%= link_to(post.user) do %>
          <%= image_tag post.user.get_image(80,80) %><br>
          <p class="text-center"><%= post.user.nickname %></p>
        <% end %>
      </td>
      <td style="width:80px;"></td>
      <td>
        <%= link_to post_path(post) do %>
          <p class="post-title"><%= post.title %></p>
        <% end %>
      </td>
    </table>
    <table style="display:flex">
      <td>
        <i class="fas fa-tag"></i>
        <% if post.tags.present? %>
          <% post.tags.each do |tag| %>
            <%= link_to tag.name, search_path(range: "Tag", word: tag.name) %>
          <% end %>
        <% else %>
          タグ無し
        <% end %>
      </td>
      <td style="width:40px;"></td>
      <td id="favorite_buttons_<%= post.id %>">
        <%= render 'favorites/favorite_btn', post: post %>
      </td>
      <td style="width:20px;"></td>
      <td>コメント：<%= post.comments.count %>件</td>
    </table>
  <p class="text-right mb-0">投稿日：<%= post.created_at.strftime('%y年%m月%d日') %></p>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render 'layouts/errors', obj: @post %>
<div class="container">
  <div class="row">
    <div class="col">
      <div class="text-center">
        <h2 class="heading mt-4">投稿編集ページ</h2>
      </div>
      <%= form_with model: @post do |f| %>
        <div class="field col-md-6 col-sm-11 mt-3 mx-auto">
          <%= f.label :タイトル, class: 'font-weight-bold' %>
          <%= f.text_field :title, autoforcus: true, class: 'form-control' %>
        </div>

        <div class="field col-md-6 col-sm-11 mt-3 mx-auto">
          <%= f.label :投稿内容, class: 'font-weight-bold' %>
          <%= f.text_area :body, class: 'form-control', rows: 5 %>
        </div>

        <div class="field col-md-6 col-sm-11 mt-3 mx-auto">
          <%= f.label"タグ (,で区切ると複数タグ登録できます)" %>
          <%= f.text_field :name, value: @tags ,class:"form-control"%>
        </div>

        <div class="action col-md-6 col-sm-11 text-right mt-3 mx-auto">
          <%= f.submit "変更", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 offset-1">
      <h2 class="heading mt-4">投稿一覧</h2>
    </div>
    <div class="col-xl-3 col-sm-11 side m-2">
      <%= render 'users/info', user: current_user %>
    </div>
    <div class="col-xl-8 col-sm-11">
      <div class="mt-4">
        <%= render 'index', posts: @posts %>
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h2 class="heading mt-4"><%= @post.title %></h2>
    </div>
    <div class="col-xl-3 col-sm-11 side m-2">
      <%= render 'users/info', user: current_user %>
    </div>

    <div class="col-xl-8 col-sm-11">
      <div class="col box">
        <table class="table table-borderless">
          <tr>
            <th style="width:80px;"><%= image_tag @post.user.get_image(80,80) %></th>
            <th class="align-middle col-3">
              <%= link_to user_path(@post.user_id) do %>
                <%= @post.user.nickname %>
              <% end %>
            </th>
            <th class="align-middle" id="favorite_buttons_<%= @post.id %>"><%= render 'favorites/favorite_btn', post: @post %></th>
            <% if @post.user_id == current_user.id %>
              <div class="text-right">
                <th class="align-bottom"><%= link_to "投稿を編集", edit_post_path(params[:id]), class: 'btn btn-success btn-sm' %></th>
                <th class="align-bottom"><%= link_to "投稿を削除", post_path(params[:id]), method: :delete, class: 'btn btn-danger btn-sm' %></th>
              </div>
            <% end %>
          </tr>
          <tr>
            <td colspan="5"><%= safe_join(@post.body.split("\n"),tag(:br)) %></td>
          </tr>
          <tr>
            <td colspan="5">
              <i class="fas fa-tag"></i>
              <% if @tags.present? %>
                <% @tags.each do |tag| %>
                  <%= link_to tag.name, search_path(range: "Tag", word: tag.name) %>
                <% end %>
              <% else %>
                タグ無し
              <% end %>
            </td>
          </tr>
          <tr class="text-right">
            <td colspan="5">投稿日:<%= @post.created_at.strftime('%m月%d日%H:%M') %></td>
          </tr>
        </table>
      </div>
      
      <h3 class="mt-3 text-center">コメント</h3>
      <div class="comment" id="posts_comment_<%= @post.id %>_list">
        <%= render 'comments/comment_list', post: @post %>
      </div>
      <div class="comment" id="posts_comment_<%= @post.id %>">
        <%= render 'comments/comment', post: @post, comment: @comment %>
      </div>
    </div>

  </div>
</div>